### PR TITLE
Warn before closing Translations table modal

### LINKED ISSUE #2006: Warn users before destroying the translation editor modal
## Description

When editing translations, clicking outside the modal closes the modal suddenly, without prompting. All changes are lost.

## Steps to Reproduce

1. Create a form
2. Click "..." ("More Actions"), "Manage Translations"
3. Create a translation if necessary
4. Click "Update translations" (globe)
5. Do some work translating your labels
6. Click outside the modal (oops!)
7. Notice that the modal has vanished
8. Open "Manage Translations" again
9. Notice that your work is gone

## Expected behavior 

I should have to click the "X" to close the modal. Preferably, I should be prompted to make sure I want to discard my unsaved changes.

## Actual behavior 

Clicking anywhere outside the modal closes it. Unsaved changes are discarded without prompting.

## Additional details

I heard you had this guy named Leszek on your team, and he's a really good developer. I'm sure he'll get this sorted out in no time flat.

### LINKED ISSUE #2011: Clicking "Manage translations" from the form list "More Actions" doesn't work
## Description

"Manage Translations" (capital-T translations) works fine when invoked from "More Actions" in the form landing page, e.g. http://172.17.0.1:8000/#/forms/aX5QEeB5TFRoW7rF7nkV3r/landing. However, when trying to open it from the form list's "More Actions" &rightarrow; "Manage translations" (lowercase-t), the app crashes and displays a white screen.

## Steps to Reproduce

1. Use `master` (at https://github.com/kobotoolbox/kpi/commit/d14e0ba318efddd14a32eb0b6ac4c7e68fc53bef)
2. See description above.

## Expected behavior 

The modal opens without crashing the app ;)

## Actual behavior 

The app crashes

## Additional details

In the form list, there's no `this.props.params.assetid`, so a `null` gets passed to `MainHeader`:
https://github.com/kobotoolbox/kpi/blob/d14e0ba318efddd14a32eb0b6ac4c7e68fc53bef/jsapp/js/app.es6#L135-L137

...which doesn't go well when it's time to `render()`:
https://github.com/kobotoolbox/kpi/blob/d14e0ba318efddd14a32eb0b6ac4c7e68fc53bef/jsapp/js/components/header.es6#L230-L233

image

### PR DESCRIPTION
**Pull request by magicznyleszek**
## Description

Works on all: Escape key, backdrop click and "X" button click. Code allows for adding same functionality in other modals.

## Related issues

Fixes #2006
Fixes #2011

### CODE REVIEW

**Comment by jnm** [comment]
I deployed this to `unu` and the app crashes (blank screen) when I open the translations modal:
image

I haven't had a chance to see if it's a problem with that development server yet.

**Comment by jnm** [comment]
Same issue with `master` branch deployed to `unu`. Trying locally...

**Comment by magicznyleszek** [comment]
@jnm I'v added confirm for BACK button and updated some text labels. 

I also found an easy way to know if there are unsaved changes and only apply BACK confirm then.

Do you think it's worthwhile to apply this logic to modal's close/backdrop click? It would be a bit more complex, as the code for closing modal is completely separated from modal's content code.

**Comment by jnm** [comment]
@magicznyleszek, I think it's worthwhile but less urgent. Could you create an issue for that and prioritize it as you see fit?

**Pull request merged**
