### PR TITLE
Rework submission modal

### LINKED ISSUE #2086: Repeat questions don't show up in the data table
This makes it impossible to filter/search based on the answers to the repeat questions

### LINKED ISSUE #2137: Nested repeated group breaks submission detail view
## Description

If you have a repeated group inside repeated group, submission detail view is broken

## Steps to Reproduce

1. Use this form: [nested-repeater-bug.xls.zip](https://github.com/kobotoolbox/kpi/files/2700074/nested-repeater-bug.xls.zip)
2. Add any submission
3. Go to Table View and open submissions detail (eye icon)
4. Observe a crash

## Additional details

May be connected to:

- #1994
- #1931
- #1574

### LINKED ISSUE #2207: Data > Table View not working
## Description

Clicking on Data Tab/Table View shows blank screen.

## Steps to Reproduce

1. Clone the latest kobo-docker, everything works OK except:

2.  After submissions of collected data, checking the records by clicking on Data > Table

## Expected behavior 
Should show the table of the submitted survey.

## Actual behavior 
It just gives a blank screen.

## Additional details
I checked the logs on my google-chrome Dev Console and got this **"TypeError: Cannot read property 'filter' of undefined"**

### LINKED ISSUE #2651: Expose _submitted_by in the table view and submission modal
I wouldn't touch the submission modal until after https://github.com/kobotoolbox/kpi/pull/2650 is merged, but please make it so that `_submitted_by` appears in that modal and in the table view. Right now, it's excluded by https://github.com/kobotoolbox/kpi/blob/81f5ba420bc366d13cd1fbed66769d4fe487dc7f/jsapp/js/components/table.es6#L159-L173

To test this, enable "Require authentication to see forms and submit data" in your account settings, and then submit some data with Enketo. Enketo should require you to log in, and your username should then appear in `_submitted_by` for all the submissions you create.

Related: https://github.com/kobotoolbox/kpi/issues/2517

### PR DESCRIPTION
**Pull request by magicznyleszek**
## Description

Reworked submission modal table for displaying responses data. Added some test for utility functions. Added `_submitted_by` to be displayed in table and in modal. Displaying repeat group answers in table view.

## Related issues

Fixes #2651
Part of #2086 
Fixes #2207
Fixes #2137 
… and possibly something else 😎

### CODE REVIEW

**Comment by jnm** [comment]
Add a note on https://www.flowdock.com/app/kobotoolbox/support/threads/HhMbPOMNIIi_3oYVvrpBQmMAR4U when this is merged

**Comment by magicznyleszek** [comment]
@duvld fixed merge conflicts :)

**Comment by duvld** [comment]
This looks like there's a lot to check so I'll post things I find periodically here to not lose track:

It looks like this code messes up your solution to the matrix problem in #2249: (using [this form](https://github.com/kobotoolbox/kpi/files/5097993/favourite-pasteries.xlsx))

`master`

image

`2086-repeat-in-table-2`

image

**Comment by magicznyleszek** [comment]
@duvld I pushed a fix to the broken matrix solution, and as for matrix in repeat not showing up - https://github.com/kobotoolbox/kpi/issues/2086 :)

**Comment by magicznyleszek** [comment]
I also found a new problem: a survey with a matrix question inside repeat group - the data doesn't show up in the submission modal. I am fixing this now, but this will take a while, as getting the data of a repeat group is a complex task :D

**Comment by duvld** [comment]
> I also found a new problem: a survey with a matrix question inside repeat group - the data doesn't show up in the submission modal. I am fixing this now, but this will take a while, as getting the data of a repeat group is a complex task :D

Can you check if this is the case for more than just matrix groups? For me, any question that is not a text question does not show up if it is in a repeat group. Godspeed!

**Comment by magicznyleszek** [comment]
For me all works just fine with: [repeat_person_form.xlsx](https://github.com/kobotoolbox/kpi/files/5118892/repeat_person_form.xlsx)

I also pushed a fix for submission data in submission modal for matrix inside repeat not appearing.

**Comment by magicznyleszek** [comment]
Also to be clear - this PR fixes the repeat in table in a simple way, by displaying all answer in a text list. We will make a better in future, but we need a design how it should look like

**Comment by jnm** [comment]
This had a small issue where the next/previous links did not work properly in the submission modal. That has now been fixed by https://github.com/kobotoolbox/kpi/commit/bc684453b5f6cc20f01c53da6279e00ed5628650#diff-f6651294b40eec7e8621989c093b76e12beefc31630df504ee4509e29ea88e16R86

**Pull request merged**
