### PR TITLE
Feature: bulk delete submissions

### LINKED ISSUE #1777: Allow bulk deleting submissions in table view
Similar to bulk changing of validation status. 

@jnm I don't know whether we need backend work for bulk deleting.

### LINKED ISSUE #1970: Endpoint for deleting multiple submissions
## Description

Probably a call to `${rootUrl}/assets/${uid}/submissions/` with either passing submission ids in array or a flag about deleting all submissions. We need delete all, because UI allows for selecting all submissions from all paginated pages - similarly to bulk updating approved/not approved status

### PR DESCRIPTION
**Pull request by noliveleger**
@magicznyleszek said in #2003.

> ## Description

> This PR redesigns the bulk selection UI and adds bulk delete option.

> screen shot 2018-09-25 at 11 17 50
> screen shot 2018-09-25 at 11 18 02

> ## Related issues

> Fixes #1777
> Fixes #1970

It closes #2003 and branch `bulk-delete` should be deleted.
It has been merged in `1970-bulk-delete` which has been created on top `two-databases`.

When those branches/PR are merged into master, don't forget to change base from two-databases to master to remove commits already reviewed

### CODE REVIEW

**Comment by magicznyleszek** [comment]
@noliveleger I've added one commit with some UI cleanup :)

**Comment by noliveleger** [comment]
> @noliveleger I've added one commit with some UI cleanup :)

Awesome

**Comment by noliveleger** [comment]
This PR contains FE (@magicznyleszek) & BE changes (me).

@arsea: Would you mind to review the FE changes? Let @john merge it when your review is done.

**Comment by arsea** [comment]
I can't review the FE as long as PR #2289 hasn't been approved/merged.

**Comment by noliveleger** [comment]
I'm in favor in redirect to another (`FORM` for example) because `DATA` tab should disappear if there are no data.

**Comment by jnm** [comment]
I was in favor of redirecting, too, but ultimately I decided to change the [message](https://github.com/kobotoolbox/kpi/blob/e62d831e93a1ed35cfd9ee0e154924ca14b6117f/jsapp/js/components/table.es6#L119) in the `done()` ([success](https://api.jquery.com/jQuery.ajax/)) callback from "Error: …" to something friendlier when the backend returns zero submissions. We can certainly improve on it in the future.

**Pull request merged**
