### PR TITLE
Feature: New Gallery 

### LINKED ISSUE #1349: Review and merge Gallery work from ADK
The gallery in KPI is almost ready, but it requires a review and several UI fixes before it can be merged. 

@pmusaraj to do a review of the UI and frontend code. @dorey will then review the Python code and tests. This work will be done in a new branch under the current repository, and future ADK work can be committed there (this allows us to more easily retain only the file changes relevant to the gallery.)

### LINKED ISSUE #1365: Wrap up the form gallery design updates

### PR DESCRIPTION
**Pull request by magicznyleszek**
## Description

I brought back all the functionalities of the broken `gallery` branch 🎆

Initial design: https://drive.google.com/drive/folders/13eGZhUMY-S6uNy3pHHi2RXjeFQ27LFu3

### Bugs

- [x] renaming questions in the form builder and then redeploying breaks the gallery in a strange way: submitted photos prior to renaming the questions are still there, but each shown as "Unknown question" (from quick look, each attachment returned from endpoint has `question: null`) - see a bit more info at https://github.com/kobotoolbox/kpi/issues/1349 comments
- [x] Backend fails when you upload an image with filename with UNICODE characters

### Next steps

TODO:
- [x] remove gallery paginated modal
- [x] add fullscreen button
- [x] fullscreen 12 per row
- [x] reorder by date option in main view
- [ ] load more should load ~3-4 rows
- [x] single image modal
  - [x] don't display more images
  - [ ] optional: more images from same submission
  - [x] arrows should work (should switch to neighbour images, should switch between questions too)
  - [x] link to submission modal
  - [x] optional: submission modal link back
- [x] counter in filters should update
- [x] search should stay regardless of `groupBy` setting
- [x] display empty search message, when filter returns no results

## Related issues

Fixes #1349 
Closes #1365
Supersedes #1333
Blocked by #3102

### CODE REVIEW

**Comment by noliveleger** [comment]
@magicznyleszek Unicode issue has been fixed by commit `e2cc393ae692d9543e1ae2c09e80f7b5deacff51`

**Comment by magicznyleszek** [comment]
Note on TODOs:
- "load more should load ~3-4 rows" --> this will require changes in endpoints to not use `page` + `page_size`, but `offset` and `limit`
- "optional: more images from same submission" --> currently there is no optimal way of getting same submission images without loading all possible images

**Comment by magicznyleszek** [comment]
@pmusaraj I've added some unit tests here and it's again ready to be reviewed and merged

**Comment by noliveleger** [comment]
@magicznyleszek, @jnm we need to merge https://github.com/kobotoolbox/kobocat/pull/502 first and modify this branch to handle new secured links.

**Comment by Raph33** [comment]
is this still in the work?

**Comment by magicznyleszek** [comment]
It slowed down unfortunately due to other work. The new gallery code is finished, but it requires some other PRs to be merged first. I am reminding the team about this constantly, so it will not be lost ;-)

**Pull request closed without merging**
