### PR TITLE
[Feature] Adds `background-audio` as a meta question type into formbuilder

### LINKED ISSUE #3275: Intergrate `background-audio` into the formbuilder
## Description

Split from #3193 this issue will be closed after the formbuilder half of the issue is merged into `beta`

### PR DESCRIPTION
**Pull request by duvld**
## Description

Can now add a [`background-audio` meta question](https://docs.getodk.org/form-question-types/#background-audio-recording) to forms via the formbuilder sidebar:

image

## Related issues
Formbuilder side of things of #3193 
Fixes #3275

### CODE REVIEW

**Comment by dorey** [comment]
Is `quality=voice-only` the default parameter? When i activated this value it showed up in the sidebar as being "Voice only" but then the JSON structure did not have any parameters reflected.

**Comment by duvld** [comment]
> Is `quality=voice-only` the default parameter? When i activated this value it showed up in the sidebar as being "Voice only" but then the JSON structure did not have any parameters reflected.

`voice-only` is what it will default to if there is no `quality=*` parameter specified, so yeah the default. I didn't want to add a parameter if the user wanted to keep it this quality, and only append the parameters column if they made an explicit decision  

I should probably make a comment explaining this :D

**Comment by dorey** [comment]
image
This text seems to imply that it doesn't work in ODK Collect, which is not the case. I think that in the past we have been OK referring to a generic "Collect" which could mean ODK or KoBoCollect.

**Comment by jnm** [comment]
> > Is `quality=voice-only` the default parameter? When i activated this value it showed up in the sidebar as being "Voice only" but then the JSON structure did not have any parameters reflected.
> 
> `voice-only` is what it will default to if there is no `quality=*` parameter specified, so yeah the default. I didn't want to add a parameter if the user wanted to keep it this quality, and only append the parameters column if they made an explicit decision
> 
> I should probably make a comment explaining this :D

the default could change in the future to something other than "Voice only", so i'd advocate for writing into the JSON when "Voice only" is chosen. maybe add an option to the drop down called "Default" that avoids appending the parameters column?

**Comment by duvld** [comment]
> > > Is `quality=voice-only` the default parameter? When i activated this value it showed up in the sidebar as being "Voice only" but then the JSON structure did not have any parameters reflected.
> > 
> > 
> > `voice-only` is what it will default to if there is no `quality=*` parameter specified, so yeah the default. I didn't want to add a parameter if the user wanted to keep it this quality, and only append the parameters column if they made an explicit decision
> > I should probably make a comment explaining this :D
> 
> the default could change in the future to something other than "Voice only", so i'd advocate for writing into the JSON when "Voice only" is chosen. maybe add an option to the drop down called "Default" that avoids appending the parameters column?

If the user doesn't change anything in the dropdown then no parameters would be appended, it would only append if they explicitly clicked an option. I think this would be better than a "Default" that would imply to me that there is a default that isn't "Voice-only"

**Review by dorey — APPROVED** [review]
Tested out locally and `background-audio` saves as expected in the forms.

**Pull request merged**
