### PR TITLE
Set the HttpOnly flag on the CSRF cookie

### PR DESCRIPTION
**Pull request by jnm**
Merge _after_ #2588.
Closes kobotoolbox/tasks#116.

### CODE REVIEW

**Comment by noliveleger** [comment]
@magicznyleszek, would you mind to merge and delete this branch after merging #2588. Thank you.

**Comment by jnm** [comment]
I cleared `donotmerge` based on https://github.com/kobotoolbox/kpi/pull/2588#issuecomment-597360054. If #2588 is okay, this should be too.

**Comment by noliveleger** [comment]
@magicznyleszek, @jnm I forgot to test something. I've put the flag back. 
I'll remove it (and merge) when my tests are completed.

**Comment by noliveleger** [comment]
@jnm. Do you think it can be a problem that KC does not apply the same rule?

**Comment by jnm** [comment]
@noliveleger, good question. I'll look now to see how KoBoCAT deals with AJAX CSRF.

**Comment by jnm** [comment]
Yep, good catch:
https://github.com/kobotoolbox/kobocat/blob/3a2525613a6a13f4ece887defc22891602563b80/onadata/apps/main/static/js/application.js#L44-L83

**Comment by jnm** [comment]
Updated KC: https://github.com/kobotoolbox/kobocat/pull/598

**Pull request merged**
