### PR TITLE
Show banner when user dismisses notification for going over usage limits

### PR DESCRIPTION
**Pull request by srartese**
## Checklist

1. [ ] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [x] Ensure the tests pass
4. [x] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [x] Write a description of your work suitable for publishing on [our forum](https://community.kobotoolbox.org/tag/release-notes)
6. [ ] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
7. [ ] Open an issue in the [docs](https://github.com/kobotoolbox/docs/issues/new) if there are UI/UX changes

## Description

When a user is notified that they have gone over one or multiple of their limits and they dismiss the modal this banner shows on the top of the page. The user is unable to dismiss this banner.

### CODE REVIEW

**Review by LMNTL — CHANGES_REQUESTED** [review]
Since this and #4545   contain some duplicated code, could close one one of them and condense it into one PR? It would make it easier to review, and and it would remove the need for you to duplicate any changes you make on #4545 to this branch.

**Comment by LMNTL** [comment]
> Since this and <SNIPPED> contain some duplicated code, could close one one of them and condense it into one PR? It would make it easier to review, and and it would remove the need for you to duplicate any changes you make on <SNIPPED> to this branch.

Sorry, that initial comment had the wrong PR, it should have said that #4532 and this should be combined.

**Comment by srartese** [comment]
> 
 Can do! Since i just keep pullin the other branch here I will move this one over to the one we are already reviewing.

**Comment by srartese** [comment]
Merged changes into other PR for easier review

**Pull request closed without merging**
